### ISSUE TITLE
Only Right Window?

### ISSUE THREAD

**Issue by DouglasHennrich** [HazemKhaled/SideMenu-with-NavigationWindow-for-Titanium#1]
There's a way to only have Right Window to be the `SlideMenu` ?
I know that iOS don't need to have the left window to have the right
but on Android, I always get an error when I try to have only the right window.

Or there's a way to prevent the slide to left window?
Thanks =)

**Comment by HazemKhaled** [comment]
I think better to create this issue directly into DrawerLayout module repo
https://github.com/manumaticx/Ti.DrawerLayout

**Comment by DouglasHennrich** [comment]
:)
